### ISSUE TITLE
Sometimes it throws cannot set property twin of null

### ISSUE THREAD

**Issue by SSCodeChamp** [Kcnarf/d3-voronoi-treemap#3] opened 2018-02-13 19:54 UTC
Hi @Kcnarf - Do you what triggers error cannot set property twin of null error. This algorithm works most of the time but very rarely gives this error.

I am not sure when it is happening exactly.

**Comment by Kcnarf** [comment] 2018-02-14 13:13
Hi @SSCodeChamp - no idea. I didn't saw this error during my experiments.

**Comment by SSCodeChamp** [comment] 2018-02-15 04:16
Is it related to any particular data condition in input dataset ?  Anyone else getting same error ?

**Comment by Kcnarf** [comment] 2018-02-15 08:26
It will be difficult to debug without any repeatable use case :-(

@SSCodeChamp : is the error related to the same dataset ?

**Comment by SSCodeChamp** [comment] 2018-02-16 04:12
Ok. I will try to capture the dataset.

Thank you.

**Comment by aardvark82** [comment] 2018-11-06 21:53
Hello,
Here's a dataset to reproduce the problem reliably:

This is with Voronoi v1.1.  The dataset displays properly with other treemap like vizualization like a bubble viz so hierarchy is sound. (not voronoi)

![screenshot 2018-11-06 13 49 59](https://user-images.githubusercontent.com/32086262/48096006-ff706700-e1ca-11e8-8b0f-f837b41ec0f7.png)

[d3 voronoi topics data bug.txt](https://github.com/Kcnarf/d3-voronoi-treemap/files/2555148/d3.voronoi.topics.data.bug.txt)

![screenshot 2018-11-06 13 53 01](https://user-images.githubusercontent.com/32086262/48096138-4a8a7a00-e1cb-11e8-89fc-3d97b56e894a.png)

**Comment by aardvark82** [comment] 2018-11-06 21:54
I loaded the json into the sample at: https://bl.ocks.org/Kcnarf/fa95aa7b076f537c00aed614c29bb568

**Comment by Kcnarf** [comment] 2018-11-08 09:37
@aardvark82 

Got the error when I paste your JSON data into the JS example.

Nevertheless, the JS example works fine (at least, doesn't produce the error and make a Voronoï treemap) when I tell the hierarchy to consider the 'size' attribute of each datum.
At line 112 of the JS example, use
```
hierarchy = d3.hierarchy(rootData).sum(function(d){ return d.size; });
```
instead of `
hierarchy = d3.hierarchy(rootData).sum(function(d){ return d.weight; });
`

A quick render:
![capture d ecran 2018-11-08 a 11 38 04](https://user-images.githubusercontent.com/4328986/48193530-ef7f9100-e34a-11e8-93a0-dc458e9e18f5.png)

**Comment by aardvark82** [comment] 2018-11-08 20:04
Super, got it. So the issue is when the JSON has an attribute not named weight - since a lot of D3 examples out there use size, I forgot to double check the properties names in the sample. Thank you !

**Comment by aardvark82** [comment] 2018-11-08 21:41
Curious how you defined the pentagon clipping - and we'd define a rectangle, triangle and other shapes in your Readme - is there an example with other clipping polygons than computeCirclingPolygon() ?

![screenshot 2018-11-08 13 41 26](https://user-images.githubusercontent.com/32086262/48229128-08447280-e35c-11e8-8633-22aba9fd9b1e.png)

**Comment by Kcnarf** [comment] 2018-11-09 13:22
computeCirclingPolygon is a convenient way to produce an array of verteces defining a regular convex polygon (regular = constant distance from center; convex = it is a hull without holes). In this function, set the number of points to 5 to obtain the array of verteces defining a pentagon.

To produce a rectangle/square Voronoï treemap., use the [.extent()](https://github.com/Kcnarf/d3-voronoi-treemap#voronoiTreemap_extent) or [.size()](https://github.com/Kcnarf/d3-voronoi-treemap#voronoiTreemap_size)  API instead of the _.clip()_ call (e.g. `.size([200,200])`)

To build the diamond shape used in the README, which is not a regular polygon, just use the [.clip()](https://github.com/Kcnarf/d3-voronoi-treemap#voronoiTreemap_clip) API with the adequate array of 5 verteces, which may look like `.clip([[200,0], [0, 350], [50, 400], [350, 400], [400,350]])`

**Comment by aardvark82** [comment] 2018-11-09 20:25
Merci!

**Comment by Kcnarf** [comment] 2019-02-21 09:14
Initial bug `Cannot set property 'twin' of null` fixed by https://github.com/Kcnarf/d3-weighted-voronoi/issues/3

**Closed as completed by Kcnarf** 2019-02-21 09:14 UTC

**Comment by olcaydaser** [comment] 2019-06-25 16:40
This issue occured after we initialized a json which sometimes generates "0" weight objects.
After considering this problem, we tried to set it manually to a floating number etc: '0.01' then issue resolved.

**Comment by CrashLaker** [comment] 2023-06-16 03:32
hi. i just found this error and realized that it was due to the d3vs version

`v7`
![image](https://github.com/Kcnarf/d3-voronoi-treemap/assets/4432491/23d9570d-a123-419e-af61-222f6acbc44e)

`v5`
worked
![image](https://github.com/Kcnarf/d3-voronoi-treemap/assets/4432491/f50fd877-e568-4b98-92ab-565abc280a22)
